#!/usr/bin/env bash
set -euo pipefail

# Usage:
#  tools/automate_fix_workflows.sh repos.txt
# repos.txt should contain one repo per line in the form OWNER/REPO
# Requires: gh CLI logged in (gh auth login) and python3 + pyyaml installed

REPOS_FILE=${1:-repos.txt}
BRANCH=fix/workflows-permissions
COMMIT_MSG="ci: add workflow permissions and persist-credentials for checkout"
PR_TITLE="Fix: workflow permissions & checkout credentials"
PR_BODY='This PR adds a minimal permissions block and ensures actions/checkout uses persist-credentials: true to avoid common GITHUB_TOKEN permission issues. Generated by tools/fix_github_workflows.py.'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIXER="$SCRIPT_DIR/fix_github_workflows.py"
PR_REPORT="$SCRIPT_DIR/pr_report.txt"
ERROR_REPORT="$SCRIPT_DIR/workflow_fix_errors.txt"
> "$PR_REPORT"
> "$ERROR_REPORT"

if [ ! -f "$REPOS_FILE" ]; then
  echo "Repos file not found: $REPOS_FILE" >&2
  exit 2
fi

while IFS= read -r repo || [ -n "$repo" ]; do
  repo_trim=$(echo "$repo" | tr -d '\r' | sed -e 's/^\s*//' -e 's/\s*$//')
  [ -z "$repo_trim" ] && continue
  echo "\n--- Processing $repo_trim ---"
  tmpdir=$(mktemp -d)
  git clone --depth 1 "https://github.com/$repo_trim.git" "$tmpdir/$repo_trim" || { echo "Clone failed for $repo_trim"; rm -rf "$tmpdir"; continue; }
  pushd "$tmpdir/$repo_trim" >/dev/null

  # run fixer from the central tools directory against the cloned repo path
  if [ -f "$FIXER" ]; then
    # capture stderr to collect parsing errors
    errfile=$(mktemp)
    python3 "$FIXER" "$tmpdir/$repo_trim" 2>"$errfile" || true
    if [ -s "$errfile" ]; then
      echo "=== Errors for $repo_trim ===" >> "$ERROR_REPORT"
      echo "$(cat "$errfile")" >> "$ERROR_REPORT"
      echo >> "$ERROR_REPORT"
    fi
    rm -f "$errfile"
  else
    echo "fixer not found at $FIXER, skipping" >&2
  fi

  if git status --porcelain | grep -q .; then
    # create or reset branch
    if git show-ref --verify --quiet refs/heads/$BRANCH; then
      git checkout $BRANCH
      git reset --hard
    else
      git checkout -b "$BRANCH"
    fi
    git add -A
    git commit -m "$COMMIT_MSG" || true
    git push --set-upstream origin "$BRANCH" --force

    # get default branch for base
    default_branch=$(gh repo view "$repo_trim" --json defaultBranchRef -q .defaultBranchRef.name 2>/dev/null || true)
    if [ -z "$default_branch" ]; then
      default_branch=main
    fi

    # create PR non-interactively and capture URL
    pr_url=$(gh pr create --repo "$repo_trim" --title "$PR_TITLE" --body "$PR_BODY" --head "$BRANCH" --base "$default_branch" --json url -q .url 2>/dev/null || true)
    if [ -n "$pr_url" ]; then
      echo "$repo_trim -> $pr_url" >> "$PR_REPORT"
      echo "Created PR: $pr_url"
    else
      # fallback: output web URL
      echo "Branch pushed for $repo_trim (branch: $BRANCH). Visit: https://github.com/$repo_trim/pull/new/$BRANCH" >> "$PR_REPORT"
    fi
  else
    echo "No changes for $repo_trim"
  fi

  popd >/dev/null
  rm -rf "$tmpdir"
done < "$REPOS_FILE"

echo "Done. Review opened PRs where changes were detected."
